name: Build

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        run: |
          npm ci
          npm run build
          cp package.json dist/
          cp package-lock.json dist/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: dist
          folder: dist
          target-folder: /
